CREATE DATABASE IF NOT EXISTS ELECTION_COLLEGE;

#DROP TABLE STUDENT;
#DROP TABLE VOTER;
#DROP TABLE ELECTIONS;

USE ELECTION_COLLEGE;

CREATE TABLE IF NOT EXISTS STUDENT (
  ID VARCHAR(15) PRIMARY KEY,
  NAME VARCHAR (50),
  DOB DATE,
  ADDRESS VARCHAR(200),
  MOBILE_NO VARCHAR(15),
  DEPARTMENT VARCHAR (25), 
  YEAR INT
);

CREATE TABLE IF NOT EXISTS VOTER (
  ID VARCHAR(15) PRIMARY KEY,
  DEPARTMENT VARCHAR(25),
  YEAR INT, 
  FOREIGN KEY (ID) REFERENCES STUDENT (ID)
);

CREATE TABLE IF NOT EXISTS CANDIDATE (
    CANDIDATE_ID VARCHAR(10) PRIMARY KEY,
    ROLL_NO VARCHAR(15),
    DEPARTMENT VARCHAR(25),
    YEAR INT, 
    FOREIGN KEY (ROLL_NO) REFERENCES STUDENT(ID)
);

CREATE TABLE IF NOT EXISTS ELECTIONS (
    ELECTION_ID VARCHAR (10) PRIMARY KEY,
    NAME VARCHAR(50),
    TYPE VARCHAR (25),
    TOTAL_VOTERS INT,
    TOTAL_VOTES INT,
    DATE_OF_ELECTION Date,
    ORGANISER_ID VARCHAR(10),
    START_TIME Time,
    END_TIME Time,
    FOREIGN KEY (ORGANISER_ID) REFERENCES ORGANISATION (ID)
);

CREATE TABLE IF NOT EXISTS ORGANISATION (
    ID VARCHAR (10) PRIMARY KEY,
    NAME VARCHAR (25),
    ADDRESS VARCHAR (200),
    PHONE_NO VARCHAR(15)
);
